In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Order_ID   300 non-null    int64
 1   Date       300 non-null    object
 2   Brand      300 non-null    object
 3   Car_Model  300 non-null    object
 4   Fuel_Type  300 non-null    object
 5   Region     300 non-null    object
 6   Revenue    300 non-null    object
dtypes: int64(1), object(6)
memory usage: 16.5+ KB

In [4]:
df.head()

,Order_ID,Date,Brand,Car_Model,Fuel_Type,Region,Revenue
0,1,25-07-2024,Toyota,Fortuner,Diesel,Central,"? 36,91,400.00"
1,2,09-03-2024,Hyundai,i20,CNG,West,"? 10,76,600.00"
2,3,07-09-2024,Tata Motors,Harrier,Electric,Central,"? 23,71,900.00"
3,4,10-07-2024,Toyota,Fortuner,Diesel,South,"? 44,23,000.00"
4,5,17-10-2024,Honda,Amaze,Petrol,Central,"? 9,61,100.00"

In [5]:
df.describe(include='all')

,Order_ID,Date,Brand,Car_Model,Fuel_Type,Region,Revenue
count,300.000000,300,300,300,300,300,300
unique,NaN,205,8,32,5,5,295
top,NaN,25-01-2024,Hyundai,Hyryder,Diesel,North,"? 13,66,600.00"
freq,NaN,5,51,16,70,72,2
mean,150.500000,NaN,NaN,NaN,NaN,NaN,NaN
std,86.746758,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,75.750000,NaN,NaN,NaN,NaN,NaN,NaN
50%,150.500000,NaN,NaN,NaN,NaN,NaN,NaN
75%,225.250000,NaN,NaN,NaN,NaN,NaN,NaN
max,300.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.isnull().sum()

Order_ID     0
Date         0
Brand        0
Car_Model    0
Fuel_Type    0
Region       0
Revenue      0
dtype: int64

In [7]:
df.columns

Index(['Order_ID', 'Date', 'Brand', 'Car_Model', 'Fuel_Type', 'Region',
       'Revenue'],
      dtype='object')

In [9]:
df.columns=df.columns.str.lower()
df.columns

Index(['order_id', 'date', 'brand', 'car_model', 'fuel_type', 'region',
       'revenue'],
      dtype='object')

In [10]:
df['date'] = pd.to_datetime(df['date'])

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21412\3532345252.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['date'] = pd.to_datetime(df['date'])

In [11]:
df['month'] = df['date'].dt.month_name()

In [12]:
df[['month']]

         month
0         July
1        March
2    September
3         July
4      October
..         ...
295   December
296   February
297  September
298    January
299      April

[300 rows x 1 columns]

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df['revenue'] = df['revenue'].str.replace("?",'',regex=False).str.strip()

In [15]:
df[['revenue']]

          revenue
0    36,91,400.00
1    10,76,600.00
2    23,71,900.00
3    44,23,000.00
4     9,61,100.00
..            ...
295  18,54,700.00
296  12,23,400.00
297   7,38,700.00
298   8,04,700.00
299  15,37,900.00

[300 rows x 1 columns]

In [17]:
df['revenue'] = df['revenue'].str.replace(',','',regex=False).astype(float)

In [18]:
df['revenue']

0      3691400.0
1      1076600.0
2      2371900.0
3      4423000.0
4       961100.0
         ...
295    1854700.0
296    1223400.0
297     738700.0
298     804700.0
299    1537900.0
Name: revenue, Length: 300, dtype: float64

In [19]:
from sqlalchemy import create_engine

# Mysql connection
username = "root"
password = "coder"
host = "localhost"
port = "3306"
database = "sales"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

table_name = "car"
df.to_sql(table_name, engine , if_exists="replace", index=False)
pd.read_sql("Select*from car limit 5;",engine)

,order_id,date,brand,car_model,fuel_type,region,revenue,month
0,1,2024-07-25,Toyota,Fortuner,Diesel,Central,3691400.0,July
1,2,2024-03-09,Hyundai,i20,CNG,West,1076600.0,March
2,3,2024-09-07,Tata Motors,Harrier,Electric,Central,2371900.0,September
3,4,2024-07-10,Toyota,Fortuner,Diesel,South,4423000.0,July
4,5,2024-10-17,Honda,Amaze,Petrol,Central,961100.0,October